<?php

include_once('story_list.features.inc');

/**
* Implementation of hook_menu().
*/
function story_list_menu() {
  $items = array();
  // Add a menu item for the ajax callback. Change "story-list" story list to
  // the path of your Panel page.
  $items['story-list/%node/%ctools_js'] = array(
    'page callback' => 'story_list_show_story_item',
    'page arguments' => array(1, 2),
    'access arguments' => array('access content'),
  );

  return $items;
}

/**
 * Callback to show the body of a single story item.
 *
 * @param $node
 *   The node object, passed by the menu system.
 * @param $js
 *   TRUE if javascript is enabled.
 *
 * @return
 *   The output of the "story_list" view if JS is enabled, otherwise redirect to
 *   the correct path.
 */
function story_list_show_story_item($node, $js = FALSE) {
  if ($js) {
    // Get the HTML output of the view.
    // Replace "story_list" with the name of your View.
    // Replace "panel_pane_2" with the display ID of your view (you can see the
    // ID of the display by hovering over the display name).
    $output = views_embed_view('story_list', 'panel_pane_2', $node->nid);

    ctools_include('ajax');

    $commands = array();
    // Replace the existing View with the new output.
    $commands[] = ctools_ajax_command_replace('.ajax-result-pane > *', $output);

    ctools_ajax_render($commands);
    // above command will exit().
  }
  else {
    // No JS, so redirect to the correct page.
    // Replace "story-list" with the path of your Panel page.
    drupal_goto('story-list/' . $node->nid);
  }
}
